pretrained_base_model_path: "ckpts/sd-image-variations-diffusers"
pretrained_vae_path: "ckpts/sd-vae-ft-mse"
image_encoder_path: "ckpts/sd-image-variations-diffusers/image_encoder"

denoising_unet_path: "/home/vton/westchaevi/ViViD/exp_output/pre_weight/denoising_unet-10080.pth"
reference_unet_path: "/home/vton/westchaevi/ViViD/exp_output/pre_weight/reference_unet-10080.pth"
# pose_guider_path: "ckpts/ViViD/pose_guider.pth"
pose_guider_path: "/home/vton/westchaevi/ViViD/exp_output/pre_weight/pose_guider-10080.pth"

# motion_module_path: "ckpts/MotionModule/mm_sd_v15_v2.ckpt"
motion_module_path: "/home/vton/westchaevi/ViViD/exp_output/pre_weight/motion_module-10080.pth"

inference_config: "./configs/train/train.yaml"
train_config: "./configs/train/train.yaml"
weight_dtype: 'fp16'
H: 512
W: 384
L: 30


model_video_paths:
  - "data_cleve/test/videos/0050.mp4"

cloth_image_paths:
  - "data_cleve/train/cloth/0030.jpg"
  - "data_cleve/train/cloth/0037.jpg"
  - "data_cleve/train/cloth/0079.jpg"
